---
version: '3'
services:
  nginx_proxy:
    container_name: nginx_proxy
    image: nginx:stable-alpine
    volumes:
      - /root/data/frontend/dist:/usr/share/nginx/html
      - /root/data/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    restart: always
    networks:
      web_nw:
        ipv4_address: 172.20.0.3

networks:
  web_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16